import type { Metadata } from 'next';
import './globals.css';
import './refinements.css';
import './milestone/milestones.css';
import './about/about.css';
import './milestone/fixes.css';
import './resume/resume.css';
import './projects/projects.css';
import './projects/balance.css';
import './projects/featured.css';
import './projects/featured-overrides.css';
import './projects/project-detail.css';
import './projects/veriview-refinements.css';
import './projects/veriview-card.css';
import './home-work.css';
import './projects/cursor-refinement.css';
import './projects/project-case-refinements.css';
import './projects/tone-art.css';
import './responsive.css';
import './responsive-final.css';
import './mobile-navigation.css';
import './mobile-floating-menu.css';
import './mobile-menu-refinements.css';
import './collaboration-logos.css';
import './projects/hotel-case-rebuild.css';
import './projects/hotel-image-sequence.css';
import './projects/hktv-3pl-card.css';
import './projects/mms-design-system.css';
import './projects/project-navigation.css';
import './resume-selector.css';
export const metadata: Metadata = { title: 'Kimberly Toh — Product Designer', description: 'Portfolio of Kimberly Toh, Staff Product Designer and UIUX Designer.', icons: { icon: '/assets/shared/favicon.svg' } };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="en"><body>{children}</body></html>; }
