'use client';
import { useLanguage } from './language-provider';
export const zh: Record<string, string> = {
  'nav.milestones':'我的闖關紀錄','nav.work':'我做過的酷東西','nav.me':'我是誰','nav.switch':'切換語言','nav.choose':'選擇語言','menu.open':'打開選單','menu.close':'收起選單','resume.view':'查看履歷','resume.options':'挑選履歷版本','footer.mail':'找我聊聊','back.top':'回到最上面','back.work':'← 返回我做過的酷東西','back.milestones':'← 返回我的闖關紀錄','back.home':'← 返回首頁','back.previous':'← 返回上一頁','project.previous':'上一個作品','project.next':'下一個作品','project.previousUnavailable':'已經是第一個作品','project.nextUnavailable':'已經是最後一個作品','project.view':'進去看看','milestone.expand':'展開里程碑','milestone.allWork':'查看更多作品',
  'home.role':'產品設計師，專攻把複雜變簡單','home.title':'把複雜梳理為清晰。','home.intro':'嗨～我是 Kimberly卓盈慧！我擅長解開打結成一團的有線耳機，產品也一樣。','home.selected':'精選作品','home.work':'我做過的酷東西','home.allWork':'查看所有作品','home.experience':'經歷','home.experience.company':'公司','home.experience.role':'職務','home.experience.period':'任職時間','home.adventures':'設計闖關紀錄','home.littleMore':'再多認識我一點','home.statement':'從喜歡美的事物開始，到今天更在意設計能不能改善你我的生活。','home.moreAbout':'來看看我的故事','home.strengths':'核心專長','home.tools':'工具','home.collaboration':'合作夥伴','home.collaborationTitle':'好設計，從一起做事開始',
  'work.selected':'精選作品','work.title':'這些，是我親手捏出來的。','work.intro':'收錄產品、UIUX、品牌、包裝與數位體驗等不同領域的作品。','about.eyebrow':'再多一點點的','about.title':'Kimberly','about.p1':'我在馬來西亞婆羅洲長大，從小就愛美好的東西。當找不到最符合個人審美的，就自己做；做著做著，創作成了本能。','about.p2':'從學習多媒體設計開始，但接觸 UIUX 後，徹底改變了我對設計的理解。設計不只是用來欣賞，它可以被使用、解決真實問題，並創造有意義的價值。這份體悟也帶領我走上產品設計這條路。','about.p3':'如今，我以邏輯、系統化與實驗性的思維面對複雜問題。與產品團隊緊密合作、一步步梳理複雜性，是我認為設計最有價值的地方；我始終相信，易用性應優先於裝飾。','about.p4':'自 2021 年起定居台北，設計以外，我用旅行收集新的地方與觀點。我最想做的產品，是讓人用了之後真心覺得「有它真好」。',
  'milestone.title':'從把故事說好，到把系統做好。','milestone.2026':'把 HKTVmall 帶進另一個市場','milestone.2024':'晉升為超資深產品設計師','milestone.2023':'把複雜營運，轉化為GMV成長','milestone.2021':'打造獲獎肯定的科技體驗','milestone.2019':'把旅宿體驗，做成想再回來的理由','milestone.2018-discover':'第一次獨自，把一座城市做成產品','milestone.2016':'30 天，22 種產業的設計衝刺','milestone.2015':'為古晉馬拉松按下起跑鍵',
  'milestone.hktv-wechat-mini-program.title':'把 HKTVmall 帶進另一個市場','milestone.hktv-wechat-mini-program.project':'HKTVmall WeChat Mini Program','milestone.hktv-wechat-mini-program.detail':'在四個月內，將 HKTVmall 的 WeChat Mini Program 從概念帶到上線，替品牌打開新的中國市場入口。','milestone.hktv-wechat-mini-program.expand':'展開「把 HKTVmall 帶進另一個市場」',
  'milestone.2024.project':'Shoalter of HKTV Group','milestone.2024.detail':'晉升為 Staff Product Designer，開始承擔產品設計方向與團隊協作的核心責任。','milestone.2024.expand':'展開「晉升為超資深產品設計師」',
  'milestone.hktv-3pl-mms.title':'把複雜營運，轉化為GMV成長','milestone.hktv-3pl-mms.project':'HKTV 3PL Merchant Management System','milestone.hktv-3pl-mms.detail':'獨立設計 HKTV 端到端的 3PL Merchant Management System，協助擴大商戶營運規模並帶動 GMV 成長。','milestone.hktv-3pl-mms.expand':'展開「把複雜營運，轉化為GMV成長」',
  'milestone.asus-veriview-armoury-crate.title':'打造獲獎肯定的科技體驗','milestone.asus-veriview-armoury-crate.project':'ASUS VeriView / ROG Armoury Crate 3.0','milestone.asus-veriview-armoury-crate.detail':'為 ASUS VeriView 設計 UI 體驗，並參與 ROG Armoury Crate 3.0 的 UI 設計，讓高效能科技產品的操作更清晰、視覺更精準。','milestone.asus-veriview-armoury-crate.expand':'展開「打造獲獎肯定的科技體驗」',
  'milestone.hotel-loyalty-reward-app.title':'把旅宿體驗，做成想再回來的理由','milestone.hotel-loyalty-reward-app.project':'Hotel Loyalty Reward App','milestone.hotel-loyalty-reward-app.detail':'把會員點數、回饋與再次入住的理由，整理成直覺好用的飯店會員體驗。','milestone.hotel-loyalty-reward-app.expand':'展開「把旅宿體驗，做成想再回來的理由」',
  'milestone.hemisphere-hotel-group.title':'讓旅宿體驗，不只停在住宿','milestone.hemisphere-hotel-group.project':'Hemisphere Hotel Group','milestone.hemisphere-hotel-group.detail':'為 Hemisphere Hotel Group 旗下飯店與度假村打造品牌與包裝設計，在各個旅客接觸點建立一致的識別。','milestone.hemisphere-hotel-group.expand':'展開「讓旅宿體驗，不只停在住宿」',
  'milestone.revpay-taobao-revenue-harvest.title':'把商業流程，做成能持續成長的體驗','milestone.revpay-taobao-revenue-harvest.project':'Revenue Harvest / revPAY / Taobao','milestone.revpay-taobao-revenue-harvest.detail':'第一次與國際品牌合作，把 revPAY 的 Taobao 結帳流程與 Revenue Harvest 的手持 POS 體驗，做成真正能在日常營運中使用的設計。','milestone.revpay-taobao-revenue-harvest.expand':'展開「把商業流程，做成能持續成長的體驗」',
  'milestone.discover-miri-app.project':'Discover Miri App','milestone.discover-miri-app.detail':'第一次獨立主導產品，也第一次與政府觀光單位合作。成功把探索美里的產品體驗、旅程與數位策略，從零開始做清楚。','milestone.discover-miri-app.expand':'展開「把一座城市做成產品」','milestone.discover-miri-app.link':'查看 Discover Miri ↗',
  'milestone.visit-miri-year.title':'讓一座城市被世界發現','milestone.visit-miri-year.project':'Visit Miri Year','milestone.visit-miri-year.detail':'主導觀光活動的品牌識別與網站設計，將美里的在地文化、景點與城市願景，轉化為一致的數位體驗。','milestone.visit-miri-year.expand':'展開「讓一座城市被世界發現」',
  'milestone.kit-hin.title':'讓品牌，帶著產品一起走向世界','milestone.kit-hin.project':'Kit Hin','milestone.kit-hin.detail':'替 Kit Hin 做好品牌與包裝，讓產品從一開始就準備好走進國際市場。','milestone.kit-hin.expand':'展開「讓品牌，帶著產品一起走向世界」',
  'milestone.layer-up.title':'把在地文化，做成可以一起玩的故事','milestone.layer-up.project':'Layer Up — Microsoft Malaysia Collaboration','milestone.layer-up.detail':'與 Microsoft Malaysia 合作完成 Layer Up。這項畢業專題透過互動遊戲與敘事，讓更多人認識在地文化。','milestone.layer-up.expand':'展開「把在地文化，做成可以一起玩的故事」',
  'milestone.2012.title':'從多媒體設計，開始打下基本功','milestone.2012.project':'Swinburne University of Technology, Melbourne','milestone.2012.detail':'從多媒體設計開始，逐步建立互動、視覺傳達、品牌與數位敘事的設計底子。','milestone.2012.expand':'展開「從多媒體設計，開始打下基本功」',
  'lede.HKTV 3PL MMS':'整合 3PL 服務、營運可視性與訂閱方案規劃的商戶管理系統，讓所有工作集中於同一個清晰的工作空間。','lede.KWS — Keyword Search':'把複雜的後台設定與營運邏輯，整理成團隊能持續擴充、使用起來不費力的平台。','lede.MMS Design System':'用共同語言，讓 MMS 的每一個畫面更一致、每一次設計更快。','lede.ASUS VeriView':'為銀行、收銀等商務使用者設計的第二螢幕，讓關鍵資訊更清晰。','lede.ROG Armoury Crate 3.0':'參與 ROG Armoury Crate 3.0 的 UI 與 Design System 開發，協助建立一致的介面語言，支撐高效能遊戲軟體體驗。','lede.Discover Miri':'Discover Miri 是我第一個獨立主導的產品設計專案。身為唯一設計師，我負責從研究、產品架構、使用者流程、視覺介面到元件系統的完整設計工作。','lede.Insiders Club':'把會員點數、優惠與訂房旅程接在一起，讓每次入住都更有理由回來。','lede.Revenue Investor':'把投資人關心的資訊，整理成一個打開手機就能掌握的地方。','lede.Revenue Harvest':'在上市前，替企業做一個能承接成長故事的數位門面。以 K 線圖、成長訊號與企業向上動能為靈感，建立具辨識度的企業數位形象。','lede.Grand Margherita Hotel':'讓五星飯店的品牌與數位體驗，一起換上更有記憶點的新樣子。','lede.Kuching Marathon 2016':'讓跑者從心動到報名，一路跑得更順；也讓活動多了超過1000位新參與者。',
  'project.Discover Miri.section.0.heading':'設計契機','project.Discover Miri.section.0.copy':'為 Miri 建立一個更親切的入口，整合景點、飲食、在地體驗與旅遊資訊。','project.Discover Miri.section.1.heading':'核心挑戰','project.Discover Miri.section.1.copy':'設計需要把大量旅遊內容整理成清晰、親切的旅程，協助訪客決定去哪裡、做什麼，以及如何探索城市。','project.Discover Miri.section.2.heading':'負責範圍','project.Discover Miri.section.2.copy':'本案由我全程負責研究、產品結構、流程、線框、介面、視覺語言與元件設計。','project.Discover Miri.section.3.heading':'打造使用者旅程','project.Discover Miri.section.3.copy':'涵蓋規劃、探索、地圖、搜尋與收藏，讓 Miri 在旅前與旅中都更好探索。','project.Discover Miri.section.4.heading':'建立一致的系統','project.Discover Miri.section.4.copy':'清晰的元件模式與整體色彩，構成一套親切且一致的旅遊產品體驗。','project.Discover Miri.image.final':'Discover Miri 專案的研究、流程、線框與行動介面設計',
  'project.Insiders Club.section.0.heading':'設計契機','project.Insiders Club.section.0.copy':'需把會員福利、點數、酒店探索與優惠整合為清楚實用的會員旅程。','project.Insiders Club.section.1.heading':'會員旅程','project.Insiders Club.section.1.copy':'以回訪住客為核心，串連探索、訂房、付款與確認流程。','project.Insiders Club.section.2.heading':'連貫的忠誠體驗','project.Insiders Club.section.2.copy':'清楚的模式與親切的 UI，幫助會員理解權益，並自在地在酒店、優惠與預訂之間切換。','project.Insiders Club.image.final':'Insiders Club 的會員 App 流程與 UI設計',
  'project.ROG Armoury Crate 3.0.section.0.heading':'背景','project.ROG Armoury Crate 3.0.section.0.copy':'Armoury Crate 將系統控制、效能設定、燈光、巨集與裝置管理整合成一套遊戲軟體體驗。','project.ROG Armoury Crate 3.0.section.1.heading':'設計貢獻','project.ROG Armoury Crate 3.0.section.1.copy':'透過 UI 設計與 Design System 工作支援專案，協助在關鍵產品畫面建立一致的元件行為、介面層級與視覺語言。','project.ROG Armoury Crate 3.0.section.2.heading':'介面演進','project.ROG Armoury Crate 3.0.section.2.copy':'Armoury Crate 3.0 走向更現代且具未來感的介面風格，在高密度系統控制與更清晰的結構、視覺層級之間取得平衡。','project.ROG Armoury Crate 3.0.section.3.heading':'Design System 支援','project.ROG Armoury Crate 3.0.section.3.copy':'參與建立可重用的 UI 模式，包括按鈕、下拉選單、分頁、滑桿、切換鈕、核取方塊與共用介面狀態。','project.ROG Armoury Crate 3.0.image.final':'ROG Armoury Crate 3.0 interface exploration, UI kit, component system, and final software screens','project.ROG Armoury Crate 3.0.aria.caseStudy':'ROG Armoury Crate 3.0 case study','project.ROG Armoury Crate 3.0.seo.title':'ROG Armoury Crate 3.0｜遊戲軟體 UI 設計｜Kimberly Toh','project.ROG Armoury Crate 3.0.seo.description':'參與 ASUS ROG Armoury Crate 3.0 的 UI 與 Design System 設計，讓高效能遊戲軟體控制更清楚有序。',
  'milestone.corporate-web-design-sprint.project':'Corporate Web Design Sprint','milestone.corporate-web-design-sprint.detail':'用 30 天完成 22 種不同的網站題目，也練出快速理解產業的能力。','milestone.corporate-web-design-sprint.expand':'展開「30 天，22 種產業的設計衝刺」',
  'milestone.kuching-marathon.project':'Kuching Marathon 2016','milestone.kuching-marathon.detail':'從網站識別到報名流程，替 Kuching Marathon 設計一條讓跑者願意起跑的數位旅程。','milestone.kuching-marathon.expand':'展開「為古晉馬拉松按下起跑鍵」','milestone.kuching-marathon.link':'進去看看這個作品 ↗',
  'milestone.2015-career.title':'設計職涯的起點','milestone.2015-career.project':'Core System Technologies','milestone.2015-career.detail':'從 Core System Technologies 開始，將設計帶進真實商業場景與不同產業。','milestone.2015-career.expand':'展開「設計職涯的起點」','milestone.timelineAria':'Kimberly Toh 的職涯里程碑',
  'collaboration.aria':'Kimberly 的合作夥伴','collaboration.category.Shoalter':'產品設計夥伴','collaboration.category.HKTVmall':'產品設計夥伴','collaboration.category.ASUS':'HQ 設計中心','collaboration.category.Hemisphere Hotel Group':'應用程式 UI/UX 設計','collaboration.category.Revenue Harvest':'網站 UI/UX 設計','collaboration.category.revPAY':'應用程式 UI/UX 與品牌體驗','collaboration.category.Visit Miri':'旅遊品牌與數位設計','collaboration.category.Grand Margherita Hotel':'品牌與數位體驗設計'
};
export function useTranslation() { const { language } = useLanguage(); return (key: string, english: string) => language === 'zh' ? zh[key] || english : english; }
